package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGCapabilities extends AttributeContainer implements KvmSerializable
{

    
    public COGAnalyticsCapabilities Analytics;
    
    public COGDeviceCapabilities Device;
    
    public COGEventCapabilities Events;
    
    public COGImagingCapabilities Imaging;
    
    public COGMediaCapabilities Media;
    
    public COGPTZCapabilities PTZ;
    
    public COGCapabilitiesExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Analytics"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Analytics = (COGAnalyticsCapabilities)__envelope.get(j,COGAnalyticsCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Device"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Device = (COGDeviceCapabilities)__envelope.get(j,COGDeviceCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Events"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Events = (COGEventCapabilities)__envelope.get(j,COGEventCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Imaging"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Imaging = (COGImagingCapabilities)__envelope.get(j,COGImagingCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Media"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Media = (COGMediaCapabilities)__envelope.get(j,COGMediaCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("PTZ"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PTZ = (COGPTZCapabilities)__envelope.get(j,COGPTZCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGCapabilitiesExtension)__envelope.get(j,COGCapabilitiesExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Analytics!=null?this.Analytics:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Device!=null?this.Device:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Events!=null?this.Events:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Imaging!=null?this.Imaging:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Media!=null?this.Media:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.PTZ!=null?this.PTZ:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = COGAnalyticsCapabilities.class;
            info.name = "Analytics";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = COGDeviceCapabilities.class;
            info.name = "Device";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGEventCapabilities.class;
            info.name = "Events";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = COGImagingCapabilities.class;
            info.name = "Imaging";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = COGMediaCapabilities.class;
            info.name = "Media";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = COGPTZCapabilities.class;
            info.name = "PTZ";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==6)
        {
            info.type = COGCapabilitiesExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

