package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGDot11SecurityConfiguration extends AttributeContainer implements KvmSerializable
{

    
    public COGEnums.Dot11SecurityMode Mode=COGEnums.Dot11SecurityMode.None;
    
    public COGEnums.Dot11Cipher Algorithm;
    
    public COGDot11PSKSet PSK;
    
    public String Dot1X;
    
    public COGDot11SecurityConfigurationExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Mode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Mode = COGEnums.Dot11SecurityMode.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.Dot11SecurityMode){
                    this.Mode = (COGEnums.Dot11SecurityMode)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Algorithm"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Algorithm = COGEnums.Dot11Cipher.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.Dot11Cipher){
                    this.Algorithm = (COGEnums.Dot11Cipher)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PSK"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PSK = (COGDot11PSKSet)__envelope.get(j,COGDot11PSKSet.class,false);
            }
            return true;
        }
        if (info.name.equals("Dot1X"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Dot1X = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Dot1X = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGDot11SecurityConfigurationExtension)__envelope.get(j,COGDot11SecurityConfigurationExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Mode!=null?this.Mode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Algorithm!=null?this.Algorithm.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.PSK!=null?this.PSK:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Dot1X!=null?this.Dot1X:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Mode";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Algorithm";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGDot11PSKSet.class;
            info.name = "PSK";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Dot1X";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = COGDot11SecurityConfigurationExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

