package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGDeviceCapabilities extends AttributeContainer implements KvmSerializable
{

    
    public String XAddr;
    
    public COGNetworkCapabilities Network;
    
    public COGSystemCapabilities System;
    
    public COGIOCapabilities IO;
    
    public COGSecurityCapabilities Security;
    
    public COGDeviceCapabilitiesExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("XAddr"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.XAddr = j.toString();
                    }
                }
                else{
                    this.XAddr = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("Network"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Network = (COGNetworkCapabilities)__envelope.get(j,COGNetworkCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("System"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.System = (COGSystemCapabilities)__envelope.get(j,COGSystemCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("IO"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.IO = (COGIOCapabilities)__envelope.get(j,COGIOCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Security"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Security = (COGSecurityCapabilities)__envelope.get(j,COGSecurityCapabilities.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGDeviceCapabilitiesExtension)__envelope.get(j,COGDeviceCapabilitiesExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return XAddr;
        }
        if(propertyIndex==1)
        {
            return this.Network!=null?this.Network:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.System!=null?this.System:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.IO!=null?this.IO:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Security!=null?this.Security:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "XAddr";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = COGNetworkCapabilities.class;
            info.name = "Network";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGSystemCapabilities.class;
            info.name = "System";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = COGIOCapabilities.class;
            info.name = "IO";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = COGSecurityCapabilities.class;
            info.name = "Security";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = COGDeviceCapabilitiesExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

