package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGDeviceServiceCapabilities extends AttributeContainer implements KvmSerializable
{

    
    public COGNetworkCapabilities_1 Network;
    
    public COGSecurityCapabilities_1 Security;
    
    public COGSystemCapabilities_1 System;
    
    public COGMiscCapabilities Misc;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Network"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Network = (COGNetworkCapabilities_1)__envelope.get(j,COGNetworkCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("Security"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Security = (COGSecurityCapabilities_1)__envelope.get(j,COGSecurityCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("System"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.System = (COGSystemCapabilities_1)__envelope.get(j,COGSystemCapabilities_1.class,false);
            }
            return true;
        }
        if (info.name.equals("Misc"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Misc = (COGMiscCapabilities)__envelope.get(j,COGMiscCapabilities.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Network;
        }
        if(propertyIndex==1)
        {
            return Security;
        }
        if(propertyIndex==2)
        {
            return System;
        }
        if(propertyIndex==3)
        {
            return this.Misc!=null?this.Misc:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = COGNetworkCapabilities_1.class;
            info.name = "Network";
            info.namespace= "http://www.onvif.org/ver10/device/wsdl";
        }
        if(propertyIndex==1)
        {
            info.type = COGSecurityCapabilities_1.class;
            info.name = "Security";
            info.namespace= "http://www.onvif.org/ver10/device/wsdl";
        }
        if(propertyIndex==2)
        {
            info.type = COGSystemCapabilities_1.class;
            info.name = "System";
            info.namespace= "http://www.onvif.org/ver10/device/wsdl";
        }
        if(propertyIndex==3)
        {
            info.type = COGMiscCapabilities.class;
            info.name = "Misc";
            info.namespace= "http://www.onvif.org/ver10/device/wsdl";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

