package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

//If you have a compilation error here then you have to add a reference to ExKsoap2.jar to your project (you can find it in Libs folder in the generated zip file)
public class COGExtendedSoapSerializationEnvelope extends com.easywsdl.exksoap2.serialization.ExSoapSerializationEnvelope {
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();
    
    static {
        classNames.put("http://www.w3.org/2004/08/xop/include^^Include",COGInclude.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector",COGVector.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Rectangle",COGRectangle.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Color",COGColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceEntity",COGDeviceEntity.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FloatRange",COGFloatRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSource",COGVideoSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension",COGVideoSourceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension2",COGVideoSourceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioSource",COGAudioSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoResolution",COGVideoResolution.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutput",COGVideoOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutputExtension",COGVideoOutputExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioOutput",COGAudioOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Scope",COGScope.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterface",COGNetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension",COGNetworkInterfaceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot3Configuration",COGDot3Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension2",COGNetworkInterfaceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceLink",COGNetworkInterfaceLink.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceConnectionSetting",COGNetworkInterfaceConnectionSetting.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceInfo",COGNetworkInterfaceInfo.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6NetworkInterface",COGIPv6NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4NetworkInterface",COGIPv4NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4Configuration",COGIPv4Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6Configuration",COGIPv6Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6ConfigurationExtension",COGIPv6ConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkProtocol",COGNetworkProtocol.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkProtocolExtension",COGNetworkProtocolExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkHost",COGNetworkHost.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkHostExtension",COGNetworkHostExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPAddress",COGIPAddress.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv4Address",COGPrefixedIPv4Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv6Address",COGPrefixedIPv6Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^HostnameInformation",COGHostnameInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^HostnameInformationExtension",COGHostnameInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DNSInformation",COGDNSInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DNSInformationExtension",COGDNSInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NTPInformation",COGNTPInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NTPInformationExtension",COGNTPInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DynamicDNSInformation",COGDynamicDNSInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DynamicDNSInformationExtension",COGDynamicDNSInformationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfiguration",COGNetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfigurationExtension",COGNetworkInterfaceSetConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6NetworkInterfaceSetConfiguration",COGIPv6NetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4NetworkInterfaceSetConfiguration",COGIPv4NetworkInterfaceSetConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkGateway",COGNetworkGateway.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11Configuration",COGDot11Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfiguration",COGDot11SecurityConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfigurationExtension",COGDot11SecurityConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSet",COGDot11PSKSet.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSetExtension",COGDot11PSKSetExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceSetConfigurationExtension2",COGNetworkInterfaceSetConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Capabilities",COGCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^CapabilitiesExtension",COGCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^CapabilitiesExtension2",COGCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsCapabilities",COGAnalyticsCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceCapabilities",COGDeviceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceCapabilitiesExtension",COGDeviceCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventCapabilities",COGEventCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilities",COGIOCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilitiesExtension",COGIOCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IOCapabilitiesExtension2",COGIOCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MediaCapabilities",COGMediaCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MediaCapabilitiesExtension",COGMediaCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RealTimeStreamingCapabilities",COGRealTimeStreamingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RealTimeStreamingCapabilitiesExtension",COGRealTimeStreamingCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ProfileCapabilities",COGProfileCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilities",COGNetworkCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilitiesExtension",COGNetworkCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkCapabilitiesExtension2",COGNetworkCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilities",COGSecurityCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilitiesExtension",COGSecurityCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SecurityCapabilitiesExtension2",COGSecurityCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilities",COGSystemCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilitiesExtension",COGSystemCapabilitiesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemCapabilitiesExtension2",COGSystemCapabilitiesExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OnvifVersion",COGOnvifVersion.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingCapabilities",COGImagingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZCapabilities",COGPTZCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceIOCapabilities",COGDeviceIOCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DisplayCapabilities",COGDisplayCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RecordingCapabilities",COGRecordingCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SearchCapabilities",COGSearchCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReplayCapabilities",COGReplayCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReceiverCapabilities",COGReceiverCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceCapabilities",COGAnalyticsDeviceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceExtension",COGAnalyticsDeviceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemLog",COGSystemLog.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SupportInformation",COGSupportInformation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AttachmentData",COGAttachmentData.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BackupFile",COGBackupFile.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemDateTime",COGSystemDateTime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SystemDateTimeExtension",COGSystemDateTimeExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DateTime",COGDateTime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Date",COGDate.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Time",COGTime.class);
        classNames.put("http://www.onvif.org/ver10/schema^^TimeZone",COGTimeZone.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RemoteUser",COGRemoteUser.class);
        classNames.put("http://www.onvif.org/ver10/schema^^User",COGUser.class);
        classNames.put("http://www.onvif.org/ver10/schema^^UserExtension",COGUserExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutputSettings",COGRelayOutputSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutput",COGRelayOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DigitalInput",COGDigitalInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNode",COGPTZNode.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension",COGPTZNodeExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension2",COGPTZNodeExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupported",COGPTZPresetTourSupported.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupportedExtension",COGPTZPresetTourSupportedExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpaces",COGPTZSpaces.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpacesExtension",COGPTZSpacesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space2DDescription",COGSpace2DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space1DDescription",COGSpace1DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration",COGFocusConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings",COGImagingSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension",COGImagingSettingsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure",COGExposure.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange",COGWideDynamicRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation",COGBacklightCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance",COGWhiteBalance.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings20",COGImagingSettings20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension20",COGImagingSettingsExtension20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension202",COGImagingSettingsExtension202.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension203",COGImagingSettingsExtension203.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension204",COGImagingSettingsExtension204.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilization",COGImageStabilization.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilizationExtension",COGImageStabilizationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustment",COGIrCutFilterAutoAdjustment.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustmentExtension",COGIrCutFilterAutoAdjustmentExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange20",COGWideDynamicRange20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation20",COGBacklightCompensation20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure20",COGExposure20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensation",COGToneCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensationExtension",COGToneCompensationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Defogging",COGDefogging.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DefoggingExtension",COGDefoggingExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NoiseReduction",COGNoiseReduction.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20",COGWhiteBalance20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20Extension",COGWhiteBalance20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20",COGFocusConfiguration20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20Extension",COGFocusConfiguration20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PaneLayout",COGPaneLayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Layout",COGLayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LayoutExtension",COGLayoutExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfiguration",COGOSDPosConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfigurationExtension",COGOSDPosConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDColor",COGOSDColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfiguration",COGOSDTextConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfigurationExtension",COGOSDTextConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfiguration",COGOSDImgConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfigurationExtension",COGOSDImgConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfiguration",COGOSDConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfigurationExtension",COGOSDConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^Service_Capabilities",COGService_Capabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^Service",COGService.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^DeviceServiceCapabilities",COGDeviceServiceCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^NetworkCapabilities",COGNetworkCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SecurityCapabilities",COGSecurityCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SystemCapabilities",COGSystemCapabilities_1.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^MiscCapabilities",COGMiscCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^UserCredential_Extension",COGUserCredential_Extension.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^UserCredential",COGUserCredential.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfigurationData_Extension",COGStorageConfigurationData_Extension.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfigurationData",COGStorageConfigurationData.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^StorageConfiguration",COGStorageConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetDeviceInformationResponse",COGGetDeviceInformationResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetDNS",COGSetDNS.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetNTP",COGSetNTP.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetServicesResponse",COGGetServicesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RestoreSystem",COGRestoreSystem.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetSystemBackupResponse",COGGetSystemBackupResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetScopesResponse",COGGetScopesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetScopes",COGSetScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^AddScopes",COGAddScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RemoveScopes",COGRemoveScopes.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^RemoveScopesResponse",COGRemoveScopesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetDPAddressesResponse",COGGetDPAddressesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetDPAddresses",COGSetDPAddresses.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetUsersResponse",COGGetUsersResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^CreateUsers",COGCreateUsers.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^DeleteUsers",COGDeleteUsers.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetUser",COGSetUser.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetCapabilities",COGGetCapabilities.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetNetworkInterfacesResponse",COGGetNetworkInterfacesResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^GetNetworkProtocolsResponse",COGGetNetworkProtocolsResponse.class);
        classNames.put("http://www.onvif.org/ver10/device/wsdl^^SetNetworkProtocols",COGSetNetworkProtocols.class);
    } 


    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public COGExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public COGExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new COGMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(writeReferenceObject(writer,obj))
        {
            return;
        }
        java.lang.Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {

            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=java.lang.String.class  )) {
                java.lang.String xmlName=COGHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    java.lang.String[] parts = xmlName.split("\\^\\^");
                    java.lang.String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        java.lang.String xsdPrefix = writer.getPrefix(xsd, true);
                        java.lang.String myType = (java.lang.String) type.type;
                        java.lang.String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }
    public SoapObject GetExceptionDetail(Element detailElement,java.lang.String exceptionElementNS,java.lang.String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }

    private Object createObject(Object soap, Class cl) throws InstantiationException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {
        Object obj=cl.newInstance();
        Method ctor = obj.getClass().getMethod("loadFromSoap",Object.class,COGExtendedSoapSerializationEnvelope.class);
        ctor.invoke(obj,soap,this);
        return obj;
    }

    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl,boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(typeFromClass)
            {
                return createObject(soap, cl);
            }
            java.lang.Object refAttr=getReference(soap);
            if (refAttr != null)
            {
                return refAttr;
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                return createObject(soap, cl);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }

    public java.lang.Object getSpecificType(java.lang.Object obj)
    {
        if(obj==null)
        {
            return null;
        }
        if(obj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)obj;
            java.lang.String key=soapObject.getNamespace()+"^^"+soapObject.getName();
            if(classNames.containsKey(key))
            {
                java.lang.Class cl=classNames.get(key);
                try
                {
                    return createObject(soapObject, cl);
                } 
                catch (java.lang.Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

        return obj;
    }

    public static java.lang.Object getXSDType(java.lang.Object param)
    {
        if(param==null)
        {
            return null;
        }
        java.lang.Class obj=param.getClass();
        if(obj.equals(java.lang.String.class))
        {
            return "string";
        }
        if(obj.equals(int.class) || obj.equals(java.lang.Integer.class))
        {
            return "int";
        }
        if(obj.equals(float.class) || obj.equals(java.lang.Float.class))
        {
            return "float";
        }
        if(obj.equals(double.class) || obj.equals(java.lang.Double.class))
        {
            return "double";
        }
        if(obj.equals(java.math.BigDecimal.class))
        {
            return "decimal";
        }
        if(obj.equals(short.class) || obj.equals(java.lang.Short.class))
        {
            return "short";
        }
        if(obj.equals(long.class) || obj.equals(java.lang.Long.class))
        {
            return "long";
        }
        if(obj.equals(boolean.class) || obj.equals(java.lang.Boolean.class))
        {
            return "boolean";
        }
        java.lang.String xmlName=COGHelper.getKeyByValue(classNames,obj);
        if(xmlName==null)
        {
            return obj;
        }
        return xmlName;
    }
} 

