package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGExposure20 extends AttributeContainer implements KvmSerializable
{

    
    public COGEnums.ExposureMode Mode=COGEnums.ExposureMode.AUTO;
    
    public COGEnums.ExposurePriority Priority;
    
    public COGRectangle Window;
    
    public Float MinExposureTime;
    
    public Float MaxExposureTime;
    
    public Float MinGain;
    
    public Float MaxGain;
    
    public Float MinIris;
    
    public Float MaxIris;
    
    public Float ExposureTime;
    
    public Float Gain;
    
    public Float Iris;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Mode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Mode = COGEnums.ExposureMode.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.ExposureMode){
                    this.Mode = (COGEnums.ExposureMode)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Priority"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Priority = COGEnums.ExposurePriority.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.ExposurePriority){
                    this.Priority = (COGEnums.ExposurePriority)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Window"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Window = (COGRectangle)__envelope.get(j,COGRectangle.class,false);
            }
            return true;
        }
        if (info.name.equals("MinExposureTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MinExposureTime = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MinExposureTime = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MaxExposureTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaxExposureTime = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MaxExposureTime = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MinGain"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MinGain = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MinGain = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MaxGain"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaxGain = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MaxGain = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MinIris"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MinIris = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MinIris = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MaxIris"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaxIris = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.MaxIris = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ExposureTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExposureTime = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.ExposureTime = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Gain"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Gain = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Gain = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Iris"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Iris = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Iris = (Float)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Mode!=null?this.Mode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Priority!=null?this.Priority.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Window!=null?this.Window:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.MinExposureTime!=null?this.MinExposureTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.MaxExposureTime!=null?this.MaxExposureTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.MinGain!=null?this.MinGain:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.MaxGain!=null?this.MaxGain:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.MinIris!=null?this.MinIris:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.MaxIris!=null?this.MaxIris:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.ExposureTime!=null?this.ExposureTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Gain!=null?this.Gain:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Iris!=null?this.Iris:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Mode";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Priority";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGRectangle.class;
            info.name = "Window";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = Float.class;
            info.name = "MinExposureTime";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = Float.class;
            info.name = "MaxExposureTime";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = Float.class;
            info.name = "MinGain";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==6)
        {
            info.type = Float.class;
            info.name = "MaxGain";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==7)
        {
            info.type = Float.class;
            info.name = "MinIris";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==8)
        {
            info.type = Float.class;
            info.name = "MaxIris";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==9)
        {
            info.type = Float.class;
            info.name = "ExposureTime";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==10)
        {
            info.type = Float.class;
            info.name = "Gain";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==11)
        {
            info.type = Float.class;
            info.name = "Iris";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

