package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGIPv4Configuration extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< COGPrefixedIPv4Address> Manual =new ArrayList<COGPrefixedIPv4Address >();
    
    public COGPrefixedIPv4Address LinkLocal;
    
    public COGPrefixedIPv4Address FromDHCP;
    
    public Boolean DHCP=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Manual"))
        {
            if(obj!=null)
            {
                if(this.Manual==null)
                {
                    this.Manual = new java.util.ArrayList< COGPrefixedIPv4Address>();
                }
                java.lang.Object j =obj;
                COGPrefixedIPv4Address j1= (COGPrefixedIPv4Address)__envelope.get(j,COGPrefixedIPv4Address.class,false);
                this.Manual.add(j1);
            }
            return true;
        }
        if (info.name.equals("LinkLocal"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LinkLocal = (COGPrefixedIPv4Address)__envelope.get(j,COGPrefixedIPv4Address.class,false);
            }
            return true;
        }
        if (info.name.equals("FromDHCP"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FromDHCP = (COGPrefixedIPv4Address)__envelope.get(j,COGPrefixedIPv4Address.class,false);
            }
            return true;
        }
        if (info.name.equals("DHCP"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DHCP = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DHCP = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.Manual.size())
        {
            java.lang.Object Manual = this.Manual.get(propertyIndex-(0));
            return Manual!=null?Manual:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==0+this.Manual.size())
        {
            return this.LinkLocal!=null?this.LinkLocal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1+this.Manual.size())
        {
            return this.FromDHCP!=null?this.FromDHCP:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2+this.Manual.size())
        {
            return DHCP;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+Manual.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.Manual.size())
        {
            info.type = COGPrefixedIPv4Address.class;
            info.name = "Manual";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.Manual.size())
        {
            info.type = COGPrefixedIPv4Address.class;
            info.name = "LinkLocal";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.Manual.size())
        {
            info.type = COGPrefixedIPv4Address.class;
            info.name = "FromDHCP";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2+this.Manual.size())
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DHCP";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

