package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGImagingSettings extends AttributeContainer implements KvmSerializable
{

    
    public COGBacklightCompensation BacklightCompensation;
    
    public Float Brightness;
    
    public Float ColorSaturation;
    
    public Float Contrast;
    
    public COGExposure Exposure;
    
    public COGFocusConfiguration Focus;
    
    public COGEnums.IrCutFilterMode IrCutFilter;
    
    public Float Sharpness;
    
    public COGWideDynamicRange WideDynamicRange;
    
    public COGWhiteBalance WhiteBalance;
    
    public COGImagingSettingsExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("BacklightCompensation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BacklightCompensation = (COGBacklightCompensation)__envelope.get(j,COGBacklightCompensation.class,false);
            }
            return true;
        }
        if (info.name.equals("Brightness"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Brightness = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Brightness = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ColorSaturation"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ColorSaturation = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.ColorSaturation = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Contrast"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Contrast = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Contrast = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Exposure"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Exposure = (COGExposure)__envelope.get(j,COGExposure.class,false);
            }
            return true;
        }
        if (info.name.equals("Focus"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Focus = (COGFocusConfiguration)__envelope.get(j,COGFocusConfiguration.class,false);
            }
            return true;
        }
        if (info.name.equals("IrCutFilter"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IrCutFilter = COGEnums.IrCutFilterMode.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.IrCutFilterMode){
                    this.IrCutFilter = (COGEnums.IrCutFilterMode)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Sharpness"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Sharpness = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Sharpness = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WideDynamicRange"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WideDynamicRange = (COGWideDynamicRange)__envelope.get(j,COGWideDynamicRange.class,false);
            }
            return true;
        }
        if (info.name.equals("WhiteBalance"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WhiteBalance = (COGWhiteBalance)__envelope.get(j,COGWhiteBalance.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGImagingSettingsExtension)__envelope.get(j,COGImagingSettingsExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BacklightCompensation!=null?this.BacklightCompensation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Brightness!=null?this.Brightness:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ColorSaturation!=null?this.ColorSaturation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Contrast!=null?this.Contrast:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Exposure!=null?this.Exposure:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Focus!=null?this.Focus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.IrCutFilter!=null?this.IrCutFilter.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Sharpness!=null?this.Sharpness:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.WideDynamicRange!=null?this.WideDynamicRange:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.WhiteBalance!=null?this.WhiteBalance:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = COGBacklightCompensation.class;
            info.name = "BacklightCompensation";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = Float.class;
            info.name = "Brightness";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = Float.class;
            info.name = "ColorSaturation";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = Float.class;
            info.name = "Contrast";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = COGExposure.class;
            info.name = "Exposure";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = COGFocusConfiguration.class;
            info.name = "Focus";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IrCutFilter";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==7)
        {
            info.type = Float.class;
            info.name = "Sharpness";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==8)
        {
            info.type = COGWideDynamicRange.class;
            info.name = "WideDynamicRange";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==9)
        {
            info.type = COGWhiteBalance.class;
            info.name = "WhiteBalance";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==10)
        {
            info.type = COGImagingSettingsExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

