package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGImagingSettingsExtension203 extends AttributeContainer implements KvmSerializable
{

    
    public COGToneCompensation ToneCompensation;
    
    public COGDefogging Defogging;
    
    public COGNoiseReduction NoiseReduction;
    
    public COGImagingSettingsExtension204 Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ToneCompensation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ToneCompensation = (COGToneCompensation)__envelope.get(j,COGToneCompensation.class,false);
            }
            return true;
        }
        if (info.name.equals("Defogging"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Defogging = (COGDefogging)__envelope.get(j,COGDefogging.class,false);
            }
            return true;
        }
        if (info.name.equals("NoiseReduction"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.NoiseReduction = (COGNoiseReduction)__envelope.get(j,COGNoiseReduction.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGImagingSettingsExtension204)__envelope.get(j,COGImagingSettingsExtension204.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ToneCompensation!=null?this.ToneCompensation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Defogging!=null?this.Defogging:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.NoiseReduction!=null?this.NoiseReduction:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = COGToneCompensation.class;
            info.name = "ToneCompensation";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = COGDefogging.class;
            info.name = "Defogging";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGNoiseReduction.class;
            info.name = "NoiseReduction";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = COGImagingSettingsExtension204.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

