package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface COGIServiceEvents
{
    public void Starting();
    public void Completed(COGOperationResult result);
}
