package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGLayout extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< COGPaneLayout> PaneLayout =new ArrayList<COGPaneLayout >();
    
    public COGLayoutExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("PaneLayout"))
        {
            if(obj!=null)
            {
                if(this.PaneLayout==null)
                {
                    this.PaneLayout = new java.util.ArrayList< COGPaneLayout>();
                }
                java.lang.Object j =obj;
                COGPaneLayout j1= (COGPaneLayout)__envelope.get(j,COGPaneLayout.class,false);
                this.PaneLayout.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGLayoutExtension)__envelope.get(j,COGLayoutExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.PaneLayout.size())
        {
            java.lang.Object PaneLayout = this.PaneLayout.get(propertyIndex-(0));
            return PaneLayout!=null?PaneLayout:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==0+this.PaneLayout.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+PaneLayout.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.PaneLayout.size())
        {
            info.type = COGPaneLayout.class;
            info.name = "PaneLayout";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.PaneLayout.size())
        {
            info.type = COGLayoutExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

