package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGNetworkInterfaceSetConfigurationExtension extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< COGDot3Configuration> Dot3 =new ArrayList<COGDot3Configuration >();
    
    public ArrayList< COGDot11Configuration> Dot11 =new ArrayList<COGDot11Configuration >();
    
    public COGNetworkInterfaceSetConfigurationExtension2 Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Dot3"))
        {
            if(obj!=null)
            {
                if(this.Dot3==null)
                {
                    this.Dot3 = new java.util.ArrayList< COGDot3Configuration>();
                }
                java.lang.Object j =obj;
                COGDot3Configuration j1= (COGDot3Configuration)__envelope.get(j,COGDot3Configuration.class,false);
                this.Dot3.add(j1);
            }
            return true;
        }
        if (info.name.equals("Dot11"))
        {
            if(obj!=null)
            {
                if(this.Dot11==null)
                {
                    this.Dot11 = new java.util.ArrayList< COGDot11Configuration>();
                }
                java.lang.Object j =obj;
                COGDot11Configuration j1= (COGDot11Configuration)__envelope.get(j,COGDot11Configuration.class,false);
                this.Dot11.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGNetworkInterfaceSetConfigurationExtension2)__envelope.get(j,COGNetworkInterfaceSetConfigurationExtension2.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.Dot3.size())
        {
            java.lang.Object Dot3 = this.Dot3.get(propertyIndex-(0));
            return Dot3!=null?Dot3:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=0+this.Dot3.size() && propertyIndex < 0+this.Dot3.size()+this.Dot11.size())
        {
            java.lang.Object Dot11 = this.Dot11.get(propertyIndex-(0+this.Dot3.size()));
            return Dot11!=null?Dot11:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==0+this.Dot3.size()+this.Dot11.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+Dot3.size()+Dot11.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.Dot3.size())
        {
            info.type = COGDot3Configuration.class;
            info.name = "Dot3";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.Dot3.size() && propertyIndex < 0+this.Dot3.size()+this.Dot11.size())
        {
            info.type = COGDot11Configuration.class;
            info.name = "Dot11";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.Dot3.size()+this.Dot11.size())
        {
            info.type = COGNetworkInterfaceSetConfigurationExtension2.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

