package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGNetworkCapabilities_1 extends AttributeContainer implements KvmSerializable
{

    
    public Boolean IPFilter=false;
    
    public Boolean ZeroConfiguration=false;
    
    public Boolean IPVersion6=false;
    
    public Boolean DynDNS=false;
    
    public Boolean Dot11Configuration=false;
    
    public Integer Dot1XConfigurations=0;
    
    public Boolean HostnameFromDHCP=false;
    
    public Integer NTP=0;
    
    public Boolean DHCPv6=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("IPFilter"))
        {	
            java.lang.Object j = inObj.getAttribute("IPFilter");
            if (j != null)
            {
                IPFilter = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("ZeroConfiguration"))
        {	
            java.lang.Object j = inObj.getAttribute("ZeroConfiguration");
            if (j != null)
            {
                ZeroConfiguration = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("IPVersion6"))
        {	
            java.lang.Object j = inObj.getAttribute("IPVersion6");
            if (j != null)
            {
                IPVersion6 = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("DynDNS"))
        {	
            java.lang.Object j = inObj.getAttribute("DynDNS");
            if (j != null)
            {
                DynDNS = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("Dot11Configuration"))
        {	
            java.lang.Object j = inObj.getAttribute("Dot11Configuration");
            if (j != null)
            {
                Dot11Configuration = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("Dot1XConfigurations"))
        {	
            java.lang.Object j = inObj.getAttribute("Dot1XConfigurations");
            if (j != null)
            {
                Dot1XConfigurations = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("HostnameFromDHCP"))
        {	
            java.lang.Object j = inObj.getAttribute("HostnameFromDHCP");
            if (j != null)
            {
                HostnameFromDHCP = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("NTP"))
        {	
            java.lang.Object j = inObj.getAttribute("NTP");
            if (j != null)
            {
                NTP = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("DHCPv6"))
        {	
            java.lang.Object j = inObj.getAttribute("DHCPv6");
            if (j != null)
            {
                DHCPv6 = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 9;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "IPFilter";
            info.namespace= "";
            if(this.IPFilter!=null)
            {
                info.setValue(this.IPFilter);
            }
            
        }
        if(index==1)
        {
            info.name = "ZeroConfiguration";
            info.namespace= "";
            if(this.ZeroConfiguration!=null)
            {
                info.setValue(this.ZeroConfiguration);
            }
            
        }
        if(index==2)
        {
            info.name = "IPVersion6";
            info.namespace= "";
            if(this.IPVersion6!=null)
            {
                info.setValue(this.IPVersion6);
            }
            
        }
        if(index==3)
        {
            info.name = "DynDNS";
            info.namespace= "";
            if(this.DynDNS!=null)
            {
                info.setValue(this.DynDNS);
            }
            
        }
        if(index==4)
        {
            info.name = "Dot11Configuration";
            info.namespace= "";
            if(this.Dot11Configuration!=null)
            {
                info.setValue(this.Dot11Configuration);
            }
            
        }
        if(index==5)
        {
            info.name = "Dot1XConfigurations";
            info.namespace= "";
            if(this.Dot1XConfigurations!=null)
            {
                info.setValue(this.Dot1XConfigurations);
            }
            
        }
        if(index==6)
        {
            info.name = "HostnameFromDHCP";
            info.namespace= "";
            if(this.HostnameFromDHCP!=null)
            {
                info.setValue(this.HostnameFromDHCP);
            }
            
        }
        if(index==7)
        {
            info.name = "NTP";
            info.namespace= "";
            if(this.NTP!=null)
            {
                info.setValue(this.NTP);
            }
            
        }
        if(index==8)
        {
            info.name = "DHCPv6";
            info.namespace= "";
            if(this.DHCPv6!=null)
            {
                info.setValue(this.DHCPv6);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

