package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGPTZNode extends COGDeviceEntity implements KvmSerializable
{

    
    public String Name;
    
    public COGPTZSpaces SupportedPTZSpaces;
    
    public Integer MaximumNumberOfPresets=0;
    
    public Boolean HomeSupported=false;
    
    public ArrayList< String> AuxiliaryCommands =new ArrayList<String >();
    
    public COGPTZNodeExtension Extension;
    
    public Boolean FixedHomePosition=false;
    
    public Boolean GeoMove=false;
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);
        if (inObj.hasAttribute("FixedHomePosition"))
        {	
            java.lang.Object j = inObj.getAttribute("FixedHomePosition");
            if (j != null)
            {
                FixedHomePosition = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("GeoMove"))
        {	
            java.lang.Object j = inObj.getAttribute("GeoMove");
            if (j != null)
            {
                GeoMove = new Boolean(j.toString());
            }
        }

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Name"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Name = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Name = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SupportedPTZSpaces"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SupportedPTZSpaces = (COGPTZSpaces)__envelope.get(j,COGPTZSpaces.class,false);
            }
            return true;
        }
        if (info.name.equals("MaximumNumberOfPresets"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaximumNumberOfPresets = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.MaximumNumberOfPresets = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("HomeSupported"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.HomeSupported = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.HomeSupported = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AuxiliaryCommands"))
        {
            if(obj!=null)
            {
                if(this.AuxiliaryCommands==null)
                {
                    this.AuxiliaryCommands = new java.util.ArrayList< String>();
                }
                java.lang.Object j =obj;
                String j1= j.toString();
                this.AuxiliaryCommands.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGPTZNodeExtension)__envelope.get(j,COGPTZNodeExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.Name!=null?this.Name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return SupportedPTZSpaces;
        }
        if(propertyIndex==count+2)
        {
            return MaximumNumberOfPresets;
        }
        if(propertyIndex==count+3)
        {
            return HomeSupported;
        }
        if(propertyIndex>=count+4 && propertyIndex < count+4+this.AuxiliaryCommands.size())
        {
            java.lang.Object AuxiliaryCommands = this.AuxiliaryCommands.get(propertyIndex-(count+4));
            return AuxiliaryCommands!=null?AuxiliaryCommands:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+4+this.AuxiliaryCommands.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+5+AuxiliaryCommands.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+1)
        {
            info.type = COGPTZSpaces.class;
            info.name = "SupportedPTZSpaces";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "MaximumNumberOfPresets";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "HomeSupported";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=count+4 && propertyIndex < count+4+this.AuxiliaryCommands.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AuxiliaryCommands";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+4+this.AuxiliaryCommands.size())
        {
            info.type = COGPTZNodeExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return super.getAttributeCount() + 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        int count=super.getAttributeCount();
        if(index==count+0)
        {
            info.name = "FixedHomePosition";
            info.namespace= "";
            if(this.FixedHomePosition!=null)
            {
                info.setValue(this.FixedHomePosition);
            }
            
        }
        if(index==count+1)
        {
            info.name = "GeoMove";
            info.namespace= "";
            if(this.GeoMove!=null)
            {
                info.setValue(this.GeoMove);
            }
            
        }
        if(index < count)
        {
            super.getAttributeInfo(index, info);
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

