package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGRectangle extends AttributeContainer implements KvmSerializable
{

    
    public Float bottom=0f;
    
    public Float top=0f;
    
    public Float right=0f;
    
    public Float left=0f;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("bottom"))
        {	
            java.lang.Object j = inObj.getAttribute("bottom");
            if (j != null)
            {
                bottom = new Float(j.toString());
            }
        }
        if (inObj.hasAttribute("top"))
        {	
            java.lang.Object j = inObj.getAttribute("top");
            if (j != null)
            {
                top = new Float(j.toString());
            }
        }
        if (inObj.hasAttribute("right"))
        {	
            java.lang.Object j = inObj.getAttribute("right");
            if (j != null)
            {
                right = new Float(j.toString());
            }
        }
        if (inObj.hasAttribute("left"))
        {	
            java.lang.Object j = inObj.getAttribute("left");
            if (j != null)
            {
                left = new Float(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 4;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "bottom";
            info.namespace= "";
            if(this.bottom!=null)
            {
                info.setValue(this.bottom);
            }
            
        }
        if(index==1)
        {
            info.name = "top";
            info.namespace= "";
            if(this.top!=null)
            {
                info.setValue(this.top);
            }
            
        }
        if(index==2)
        {
            info.name = "right";
            info.namespace= "";
            if(this.right!=null)
            {
                info.setValue(this.right);
            }
            
        }
        if(index==3)
        {
            info.name = "left";
            info.namespace= "";
            if(this.left!=null)
            {
                info.setValue(this.left);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

