package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGSystemCapabilities extends AttributeContainer implements KvmSerializable
{

    
    public Boolean DiscoveryResolve=false;
    
    public Boolean DiscoveryBye=false;
    
    public Boolean RemoteDiscovery=false;
    
    public Boolean SystemBackup=false;
    
    public Boolean SystemLogging=false;
    
    public Boolean FirmwareUpgrade=false;
    
    public ArrayList< COGOnvifVersion> SupportedVersions =new ArrayList<COGOnvifVersion >();
    
    public COGSystemCapabilitiesExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DiscoveryResolve"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DiscoveryResolve = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DiscoveryResolve = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DiscoveryBye"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DiscoveryBye = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DiscoveryBye = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RemoteDiscovery"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RemoteDiscovery = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.RemoteDiscovery = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SystemBackup"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SystemBackup = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SystemBackup = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SystemLogging"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SystemLogging = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SystemLogging = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FirmwareUpgrade"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FirmwareUpgrade = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.FirmwareUpgrade = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SupportedVersions"))
        {
            if(obj!=null)
            {
                if(this.SupportedVersions==null)
                {
                    this.SupportedVersions = new java.util.ArrayList< COGOnvifVersion>();
                }
                java.lang.Object j =obj;
                COGOnvifVersion j1= (COGOnvifVersion)__envelope.get(j,COGOnvifVersion.class,false);
                this.SupportedVersions.add(j1);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGSystemCapabilitiesExtension)__envelope.get(j,COGSystemCapabilitiesExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DiscoveryResolve;
        }
        if(propertyIndex==1)
        {
            return DiscoveryBye;
        }
        if(propertyIndex==2)
        {
            return RemoteDiscovery;
        }
        if(propertyIndex==3)
        {
            return SystemBackup;
        }
        if(propertyIndex==4)
        {
            return SystemLogging;
        }
        if(propertyIndex==5)
        {
            return FirmwareUpgrade;
        }
        if(propertyIndex>=6 && propertyIndex < 6+this.SupportedVersions.size())
        {
            java.lang.Object SupportedVersions = this.SupportedVersions.get(propertyIndex-(6));
            return SupportedVersions!=null?SupportedVersions:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==6+this.SupportedVersions.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7+SupportedVersions.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DiscoveryResolve";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DiscoveryBye";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "RemoteDiscovery";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SystemBackup";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SystemLogging";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "FirmwareUpgrade";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=6 && propertyIndex < 6+this.SupportedVersions.size())
        {
            info.type = COGOnvifVersion.class;
            info.name = "SupportedVersions";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==6+this.SupportedVersions.size())
        {
            info.type = COGSystemCapabilitiesExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

