package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGSystemDateTime extends AttributeContainer implements KvmSerializable
{

    
    public COGEnums.SetDateTimeType DateTimeType=COGEnums.SetDateTimeType.Manual;
    
    public Boolean DaylightSavings=false;
    
    public COGTimeZone TimeZone;
    
    public COGDateTime UTCDateTime;
    
    public COGDateTime LocalDateTime;
    
    public COGSystemDateTimeExtension Extension;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DateTimeType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateTimeType = COGEnums.SetDateTimeType.fromString(j.toString());
                    }
                }
                else if (obj instanceof COGEnums.SetDateTimeType){
                    this.DateTimeType = (COGEnums.SetDateTimeType)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DaylightSavings"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DaylightSavings = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DaylightSavings = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TimeZone"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TimeZone = (COGTimeZone)__envelope.get(j,COGTimeZone.class,false);
            }
            return true;
        }
        if (info.name.equals("UTCDateTime"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.UTCDateTime = (COGDateTime)__envelope.get(j,COGDateTime.class,false);
            }
            return true;
        }
        if (info.name.equals("LocalDateTime"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LocalDateTime = (COGDateTime)__envelope.get(j,COGDateTime.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGSystemDateTimeExtension)__envelope.get(j,COGSystemDateTimeExtension.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DateTimeType!=null?this.DateTimeType.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return DaylightSavings;
        }
        if(propertyIndex==2)
        {
            return this.TimeZone!=null?this.TimeZone:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.UTCDateTime!=null?this.UTCDateTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.LocalDateTime!=null?this.LocalDateTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateTimeType";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DaylightSavings";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = COGTimeZone.class;
            info.name = "TimeZone";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = COGDateTime.class;
            info.name = "UTCDateTime";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==4)
        {
            info.type = COGDateTime.class;
            info.name = "LocalDateTime";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==5)
        {
            info.type = COGSystemDateTimeExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

