package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class COGSecurityCapabilitiesExtension2 extends AttributeContainer implements KvmSerializable
{

    
    public Boolean Dot1X=false;
    
    public ArrayList< Integer> SupportedEAPMethod =new ArrayList<Integer >();
    
    public Boolean RemoteUserHandling=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Dot1X"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Dot1X = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.Dot1X = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SupportedEAPMethod"))
        {
            if(obj!=null)
            {
                if(this.SupportedEAPMethod==null)
                {
                    this.SupportedEAPMethod = new java.util.ArrayList< Integer>();
                }
                java.lang.Object j =obj;
                Integer j1= Integer.parseInt(j.toString());
                this.SupportedEAPMethod.add(j1);
            }
            return true;
        }
        if (info.name.equals("RemoteUserHandling"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RemoteUserHandling = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.RemoteUserHandling = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Dot1X;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.SupportedEAPMethod.size())
        {
            java.lang.Object SupportedEAPMethod = this.SupportedEAPMethod.get(propertyIndex-(1));
            return SupportedEAPMethod!=null?SupportedEAPMethod:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==1+this.SupportedEAPMethod.size())
        {
            return RemoteUserHandling;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+SupportedEAPMethod.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "Dot1X";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.SupportedEAPMethod.size())
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "SupportedEAPMethod";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.SupportedEAPMethod.size())
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "RemoteUserHandling";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

