package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGVideoOutput extends COGDeviceEntity implements KvmSerializable
{

    
    public COGLayout Layout;
    
    public COGVideoResolution Resolution;
    
    public Float RefreshRate;
    
    public Float AspectRatio;
    
    public COGVideoOutputExtension Extension;
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Layout"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Layout = (COGLayout)__envelope.get(j,COGLayout.class,false);
            }
            return true;
        }
        if (info.name.equals("Resolution"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Resolution = (COGVideoResolution)__envelope.get(j,COGVideoResolution.class,false);
            }
            return true;
        }
        if (info.name.equals("RefreshRate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RefreshRate = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.RefreshRate = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AspectRatio"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AspectRatio = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.AspectRatio = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGVideoOutputExtension)__envelope.get(j,COGVideoOutputExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return Layout;
        }
        if(propertyIndex==count+1)
        {
            return this.Resolution!=null?this.Resolution:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.RefreshRate!=null?this.RefreshRate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.AspectRatio!=null?this.AspectRatio:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = COGLayout.class;
            info.name = "Layout";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+1)
        {
            info.type = COGVideoResolution.class;
            info.name = "Resolution";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+2)
        {
            info.type = Float.class;
            info.name = "RefreshRate";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+3)
        {
            info.type = Float.class;
            info.name = "AspectRatio";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+4)
        {
            info.type = COGVideoOutputExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

