package com.example.xwysun.wsdltest.device;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class COGVideoSource extends COGDeviceEntity implements KvmSerializable
{

    
    public Float Framerate=0f;
    
    public COGVideoResolution Resolution;
    
    public COGImagingSettings Imaging;
    
    public COGVideoSourceExtension Extension;
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,COGExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,COGExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("Framerate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Framerate = new Float(j.toString());
                    }
                }
                else if (obj instanceof Float){
                    this.Framerate = (Float)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Resolution"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Resolution = (COGVideoResolution)__envelope.get(j,COGVideoResolution.class,false);
            }
            return true;
        }
        if (info.name.equals("Imaging"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Imaging = (COGImagingSettings)__envelope.get(j,COGImagingSettings.class,false);
            }
            return true;
        }
        if (info.name.equals("Extension"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Extension = (COGVideoSourceExtension)__envelope.get(j,COGVideoSourceExtension.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return Framerate;
        }
        if(propertyIndex==count+1)
        {
            return Resolution;
        }
        if(propertyIndex==count+2)
        {
            return this.Imaging!=null?this.Imaging:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = Float.class;
            info.name = "Framerate";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+1)
        {
            info.type = COGVideoResolution.class;
            info.name = "Resolution";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+2)
        {
            info.type = COGImagingSettings.class;
            info.name = "Imaging";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+3)
        {
            info.type = COGVideoSourceExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

