package com.example.xwysun.wsdltest.wsdl;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.3
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface KBFIServiceEvents
{
    public void Starting();
    public void Completed(KBFOperationResult result);
}
